version: '3.3'

services:
  sba-server:
    build: .
    container_name: sba-server
    ports:
      - "5757:5757"
    env_file:
      - deploy/config.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
