
server:
  port: 5757
  servlet:
    context-path: /sba-server

spring:
  boot:
    admin:
      context-path: "/sba-server"
      ui:
        public-url: "http://localhost:5757/sba-server/ui"
  security:
    user:
      name: ${SBA_SERVER_USER}
      password: ${SBA_SERVER_PASSWORD}
