
server:
  port: 5757
  servlet:
    context-path: /sba-server

spring:
  boot:
    admin:
      context-path: "/sba-server"
      ui:
        public-url: "https://185.250.46.112/sba-server"
  security:
    user:
      name: ${SBA_SERVER_USER}
      password: ${SBA_SERVER_PASSWORD}
